name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      # https://github.com/marketplace/actions/push-to-ghcr
      - name: Build and publish Docker image
        uses: macbre/push-to-ghcr@master
        with:
          image_name: ghcr.io/dcube-burnout/burnout-nestjs:latest
          github_token: ${{ secrets.CR_PAT }}
